version: '3.1'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.2
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline/
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1  
    ports: 
      - 9200:9200
    environment:
      - discovery.type=single-node
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
